### ISSUE TITLE
Function with default argument

### ISSUE THREAD

**Issue by vefaliahmet** [CopernicaMarketingSoftware/PHP-CPP#141]
is there any example about defining function with default argument?

for example;

function cpp($a = 20){
     return $a;
}

**Comment by alestrooisma** [comment]
In that case, I cannot specify any arguments when registering the function, right?

C++ and PHP both support default arguments, may I ask why PHP-CPP does not?

**Comment by EmielBruijntjes** [comment]
You can indeed not specify arguments when you register a function.

I don't think there is an answer to your second question. From a technical standpoint it would indeed have been possible to make the PHP-CPP API so that it was possible to supply default parameters. I don't remember if I had a good reason to leave it out. Maybe I just did not think about it, or maybe I decided that it would make things more complicated than necessary.

But this is an open source library, nothing stands in the way of sending in a pull requests to add this feature.
