### ISSUE TITLE
Install PHP-CPP and write first extension 

### ISSUE THREAD

**Issue by hugdx** [CopernicaMarketingSoftware/PHP-CPP#149]
Hi, i am trying install php-cpp on centos 6.5.
when i run make command, it return success. and when i run make test, i got some test which is not passed yet.
````
Number of tests :   44                44
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    8 ( 18.2%) ( 18.2%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   36 ( 81.8%) ( 81.8%)
---------------------------------------------------------------------
Time taken      :    5 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test Php::Value object #2 [php/phpt/variables/010-value-object2.phpt]
Test Php::Value casting operators (64bit OS only) [php/phpt/variables/011-value-casting-operators.phpt]
Test Php::Value casting operators (double) [php/phpt/variables/012-value-casting-operators-double.phpt]
calling-php-functions from userspace [php/phpt/variables/013-calling-php-functions.phpt]
calling-php-Callback-functions [php/phpt/variables/014-calling-php-functions.phpt]
calling-php-Callback-functions (lambda) [php/phpt/variables/015-calling-php-functions.phpt]
calling-php-Callback-functions (__invoke) [php/phpt/variables/016-calling-php-functions.phpt]
calling-php-Callback-functions (method of class) [php/phpt/variables/017-calling-php-functions.phpt]
=====================================================================
````

this is my server info
````
PHP 5.6.2 (cli) (built: Nov  6 2014 21:20:44)
Linux localhost.localdomain 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
````

When i created a hello extenstion flow http://www.sitepoint.com/getting-started-php-extension-development-via-php-cpp/ and i build success, when i test function, i get a warning:
````
[Mon Dec 08 16:34:57 2014] [error] [client 192.168.1.5] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20131226/skeleton.so' - libphpcpp.so: cannot open shared object file: No such file or directory in Unknown on line 0
````
how i can fixed it. /usr/lib/php/extensions/no-debug-non-zts-20131226/skeleton.so is exist.

main.cpp
````
#include <phpcpp.h>
#include <iostream>

void helloWorld (Php::Parameters &params)
{
    std::string name=params[0];
    std::cout<<"Hello "<<name<<"!"<<std::endl;

}

extern "C" {

    PHPCPP_EXPORT void *get_module() 
    {
        static Php::Extension extension("skeleton", "1.0");
        extension.add("helloWorld", helloWorld);

        return extension;
    }
} 
````
Makefile
````
NAME				=	skeleton
INI_DIR				=	/etc/httpd/php.d/default
EXTENSION_DIR		=	$(shell php-config --extension-dir)
EXTENSION 			=	${NAME}.so
INI 				=	${NAME}.ini
COMPILER			=	g++
LINKER				=	g++
COMPILER_FLAGS		=	-Wall -c -O2 -std=c++11 -fpic -o
LINKER_FLAGS		=	-shared
LINKER_DEPENDENCIES	=	-lphpcpp
RM					=	rm -f
CP					=	cp -f
MKDIR				=	mkdir -p
SOURCES				=	$(wildcard *.cpp)
OBJECTS				=	$(SOURCES:%.cpp=%.o)

all:					${OBJECTS} ${EXTENSION}

${EXTENSION}:			${OBJECTS}
						${LINKER} ${LINKER_FLAGS} -o $@ ${OBJECTS} ${LINKER_DEPENDENCIES}

${OBJECTS}:
						${COMPILER} ${COMPILER_FLAGS} $@ ${@:%.o=%.cpp}

install:		
						${CP} ${EXTENSION} ${EXTENSION_DIR}
						${CP} ${INI} ${INI_DIR}
				
clean:
						${RM} ${EXTENSION} ${OBJECTS}
````

skeleton.ini
````
extension=skeleton.so
````

Thanks

**Comment by jto888** [comment]
Introduction - I am Jacob Ormerod - recently commented on main web site.  I have been programming in C++ linked to R for some time.  Now interested for same success with php. I may not be a strong contirbutor on your code base, but I can promise to be a sensible tester and commenter.  I will help where I can with problems other users have. Currently I am working within a VM on Windows7.  Many Windows users are afraid of spending too much time figuring out Linux. I hope to encourage them with simple walkthrough with VM.

**Comment by jto888** [comment]
I must be missing something simple!  I have installed several linux distros from scratch over this past weekend to sharpen my skills.  My most recent experience is a Fedora21 server.  I have built the PHPCPP source and can confirm successful installation of the libphpcpp.so into /usr/lib (I note that it is the only php related item there and the only *.so file not in some sub-folder, but this is the location pointed to by PHP_SHARED_LIBRARY.)
I have followed Taylor Ren's simplistic helloworld example using a name skeleton.ini and creating skeleton.so from the EmptyExtension example.  After ' make && sudo make install ' I restarted hppd (apache on Fedora) and confirm that skeleton.ini appears in phpinfo().  When I load helloworld,php into my browser I only ever see the first echo line ' Testing helloWold in skeleton,so ' appear. once a call is made into the phpcpp extension no more execution is visible.  No error messages appear either.
I got this same result on a fresh Debian7 installation that I have since wiped out for the Fedora server.  I have given up on XAMPP installations in the VM's for now.

**Comment by hugdx** [comment]
Hi @jto888 
i fixed my frist extension. because my system is ``x64``, so ``libphpcpp.so`` should be in  ``/usr/lib64/``.
with tests, it still failed on my system.
 
Also, Thank you @valmat , @schoentoon , @EmielBruijntjes, @andot  for help me

**Comment by EmielBruijntjes** [comment]
@jto888, maybe it should indeed be installed in /usr/lib64, i've seen that report from a number of others as well.

**Comment by jto888** [comment]
Okay, I revised the Makefile so that INSTALL_LIB = ${INSTALL-PREFIX}/lib64
After make (nothing to be done) and sudo make install the libphpcpp.so is now in /usr/lib64/ along with many lib*.so companions.
I also checked the install location for skeleton.so (for my helloworld example). Indeed php-config --extension-dir reveals this as /usr/lib64/php/modules, which is where it has always been with many other friends like mysql.so
I have ultimately rebooted the system after repeated sudo service httpd restart commands, but the helloworld.php only ever results in first line as originally indicated.  I am going to try the bubblesort example and see if I get a report back after extension execution.  If this does not work I may look into another Debian family distro like Mint or Ubuntu so that things look more like everyone else.

**Comment by jto888** [comment]
Okay, its working on the Fedora server.  My php skills are not good, but I have a full run of bubblesort_test.php (with include 'bubblesort_script.php'; line added).  Yes, time improvement is factor of 10.  I'm ready to start some more serious investigations.  I don't know what went wrong with my helloworld.php copied straight from Taylor Ren.

**Comment by jto888** [comment]
Emiel,

I am intrigued by your efforts to create and promote PHPCPP.  As a 
business owner I am sure you have many other priorities!

I am now coming up to speed with this package, my approach has been a 
bit experimental.  Having only a book introduction to PHP with focus on 
MySQL integration on lampp, I have been quite surprised by the focus on 
PHP-CLI use by your co-developers.  My introductory assumption was that 
I would be executing my php scripts on a web server, specifically, 
apache.  Now I see why I was confused by 'simple' examples that called 
for use of iostream.  Those will not display on a web page, only on a 
local CLI client.

My goal is to move from R package development for my reliability 
engineering work to perhaps a web application platform.  I am very new 
to PHP, but see this as the ubiquitous back-end scripting engine 
particularly for MySQL interaction.  I have an application in mind that 
should be ideal for building a conceptual web application experience.  
Since much of my work becomes computationally intense, I realized that I 
would quickly wish to 'go native' from PHP.

As I looked at initial phpcpp example success last night, I have been 
reflecting on original purpose for my study and where it may go.  The 
mind sometimes wanders in places that are too big for the immediate.  I 
am ready now to start gaining experience with the core of my thoughts.

Eventually, I will be needing a graphical output capability.  Due to 
your experience with web development, I am curious about your thoughts 
for vector graphic presentation.  I noticed that the pcp-cairo project 
seemed to end about 3 years ago.  Is that because they did all that 
could be done?  I doubt it.  I suppose there will be a client side 
effort for my web application platform that will likely use javascript 
controlling an html5 canvas.  Any comment?

In the mean time, I am going to figure out a way to blog on my 
experience in setting up the lampp environment on a Debian7 VM for 
learning and developing using phpcpp.

Thanks again for your efforts.

Regards,
Jake

**Comment by EmielBruijntjes** [comment]
Yes, many examples are written for the PHP CLI environment. That's because such examples are the simplest, and as a developer they are the easiest to test: you can simply run `php test.php` from the same terminal window in which you were programming, without having to restart a webserver, and without having to alt-tab to a browser window. But in the real world, most of the code runs of course as webserver scripts, within apache for example, and in such environments there is no stdout.

We built PHP-CPP because we already have a very large PHP code base, and sometimes we want to speed up certain algorithms by giving them a native implementation, or we want to make use of technologies that are not available in PHP. In such situations PHP-CPP is a good solution, because it makes combining PHP and C/C++ so much easier.

But if you're completely new to PHP, I'm not sure if it is a very wise choice to start using it, especially not if you want to use it as a programming language. As far as I know, PHP was originally developed to make it possible to turn static HTML files into dynamic web pages, without the intention to be a full blown programming language. It is full of inconsistencies and peculiarities, simply because it grew organically, without a big master plan. That's also exactly how one should be using PHP: for simple scripts in web environments.

If you start using PHP for big class hierarchies, large data structures and complicated algorithms, you may be using the wrong tool. Of course, it is possible to dig a canal with a spoon - but there is better equipment around.

I have no experience with php-cairo. In fact, I had never heard of it. There are many ways to present graphical output to a user. Browsers are extremely powerful these days, and sending HTML code, a javascript and JSON encoded data to a browser is most often the simplest solution to implement. But nothing forbids you to do it completely different.

**Comment by jto888** [comment]
Emiel,

Thank you for your attention to my ramblings.

Yes, I am completely new to PHP and was never convinced I wanted to use 
it as a full fledged language for application development.  This is why 
my attention was drawn to PHP-CPP at such early point in exposure.

I am a retired engineer, but my mind cannot rest, so I work at my desk 
as hard as ever.  What is happening to me is that I can see a whole new 
avenue for development for me.  Web application development. This is 
exciting.

As an engineer, I approach all subjects similarly.  So, I suppose I am a 
software engineer without much formal practice.  I look for the 
capability in various tools and languages that will cobble together to 
form a stack for application development.  Not a single development 
environment, but a stack.  I see PHP-CPP as a critical bridge from the 
web server to C++.  There are probably commercial solutions, but without 
your open source initiative, I would never know.

One possibility that I see is to use php to populate input parameters to 
a MySQL database that C++ code can then access on a PHP-CPP call.  This 
could 'simplify' the arguments and return value requirements between php 
and C++.  The input and output would then be persistently saved in the 
database, for reuse perhaps.  Seems a better solution than creating files.

I will be very interested in running multiple threads from php code, 
which I understand is one of its strengths.  I am not sure what the 
limitation will be with PHP-CPP in terms of multi-threading.  If I am 
making calls to PHP-CPP does this mean I can't thread other processes 
from php? (at least for now).  Or does it simply mean that I cannot 
multi-thread from C++ inside the PCP-CPP framework.

As for user interface I need to look into JSON, thanks for pointing me.

Regards,
Jake

**Comment by han130634** [comment]
hello,
I am a chinese ,i am a new php-cpp user.
I had execute the 'sudo make' command , and it success,But,when i compile the php-cpp,I found one error like the down code.
g++ -Wall -c -O2 -std=c++11 -fpic -I"/usr/local/PHP-CPP/tests/include/lib" -I"/usr/local/PHP-CPP/tests/include/zts" -o main.o main.cpp
In file included from h/variables.h:19:0,
                 from main.cpp:13:
h/../include/variables/011-012-value-casting-operators.h: In function ‘void TestVariables::value_casting(Php::Parameters&)’:
h/../include/variables/011-012-value-casting-operators.h:23:17: error: conversion from ‘Php::Value’ to ‘long int’ is ambiguous
   long value1 = value;
.........
In file included from /usr/local/PHP-CPP/tests/include/lib/phpcpp.h:61:0,
                 from main.cpp:8:
/usr/local/PHP-CPP/tests/include/lib/phpcpp/class.h: In member function ‘Php::Value Php::Class<ANYTHING>::callToInteger(Php::Base*) const [with T = TestVariables::Obj2Scalar]’:
/usr/local/PHP-CPP/tests/include/lib/phpcpp/class.h:451:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/usr/local/PHP-CPP/tests/cpp'
/usr/local/PHP-CPP:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0
=====================================================================
PHP         : /usr/local/php/bin/php 
Warning: PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP_SAPI    : cli
PHP_VERSION : 5.4.8
ZEND_VERSION: 2.4.0
PHP_OS      : Linux - Linux hyqlinux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:23:46 UTC 2014 i686
INI actual  : /usr/local/php/lib/php.ini
More .INIs  :  
CWD         : /usr/local/PHP-CPP/tests
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
.........
=====================================================================
Number of tests :   44                 0
Tests skipped   :   44 (100.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

I want to know the results of the above errors would affect?
Looking forward to your reply.
best wishes. 
thks.

**Comment by Thalaivan** [comment]
I want install and use PHP-CPP  while i run test i got below error (can u help me pls)


thalaivan-desktop:/var/www/html/PHP-CPP/tests$ ./test.sh -p /usr/bin/php5 -s /tmp/tests-out
Compile the test extension
rm -f extfortest.so main.o
g++ -Wall -c -O2 -std=c++11 -fpic -I"/var/www/html/PHP-CPP/tests/include/lib" -I"/var/www/html/PHP-CPP/tests/include/zts" -o main.o main.cpp
g++ -shared -L"/var/www/html/PHP-CPP" -o extfortest.so main.o -lphpcpp
/var/www/html/PHP-CPP:

=====================================================================
PHP         : /usr/bin/php5 
PHP_SAPI    : cli
PHP_VERSION : 5.5.9-1ubuntu4.6
ZEND_VERSION: 2.5.0
PHP_OS      : Linux - Linux svasamn1-desktop 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64
INI actual  : /etc/php5/cli/php.ini
More .INIs  : /etc/php5/cli/conf.d/05-opcache.ini,/etc/php5/cli/conf.d/10-pdo.ini,/etc/php5/cli/conf.d/20-curl.ini,/etc/php5/cli/conf.d/20-gd.ini,/etc/php5/cli/conf.d/20-json.ini,/etc/php5/cli/conf.d/20-mysql.ini,/etc/php5/cli/conf.d/20-mysqli.ini,/etc/php5/cli/conf.d/20-pdo_mysql.ini,/etc/php5/cli/conf.d/20-readline.ini,/etc/php5/cli/conf.d/30-callphpfunction.ini,/etc/php5/cli/conf.d/skeleton.ini 
CWD         : /var/www/html/PHP-CPP/tests
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
Running selected tests.
PASS Test constructor & destructor [php/phpt/class_obj/001.phpt] 
PASS Test constructor & destructor [php/phpt/class_obj/002.phpt] 
PASS Test comparable objects [php/phpt/class_obj/003-comparable.phpt] 
PASS Test class with static function [php/phpt/class_obj/004-static-funct.phpt] 
PASS Test class with static property and class constant [php/phpt/class_obj/005-static-prop.phpt] 
PASS Test ini entries #1 [php/phpt/ini_entries/001.phpt] 
PASS Test ini entries #2 [php/phpt/ini_entries/002.phpt] 
PASS Test ini entries #3 [php/phpt/ini_entries/003.phpt] 
PASS Iterate array [php/phpt/valueiterator/001.phpt] 
PASS Iterate object of stdClass [php/phpt/valueiterator/002.phpt] 
PASS Iterate object [php/phpt/valueiterator/003.phpt] 
PASS Iterate itarable oblect [php/phpt/valueiterator/004.phpt] 
PASS Iterate itarable oblect [php/phpt/valueiterator/005.phpt] 
PASS Iterate itarable oblect [php/phpt/valueiterator/006.phpt] 
PASS Iterate internal array [php/phpt/valueiterator/007-Iterate-internal-array.phpt] 
PASS Global variables in PHP-CPP [php/phpt/variables/001-process_globals.phpt] 
PASS get_complex_array [php/phpt/variables/002-get_complex_array.phpt] 
PASS get_complex_array [php/phpt/variables/003-value-types.phpt] 
PASS Test variables defined in PHP-CPP [php/phpt/variables/004-store-scalar-variables.phpt] 
PASS cast objects to scalars [php/phpt/variables/005-cast-objects-to-scalars.phpt] 
PASS Test Php::Value casting operators (object to string) [php/phpt/variables/006-casting-obj2str.phpt] 
PASS Test Php::Value overloaded operators [php/phpt/variables/007-overloaded-operators.phpt] 
PASS Test Php::Value arrays [php/phpt/variables/008-value-arrays.phpt] 
PASS Test Php::Value object #1 [php/phpt/variables/009-value-object.phpt] 
PASS Test Php::Value object #2 [php/phpt/variables/010-value-object2.phpt] 
FAIL Test Php::Value casting operators (64bit OS only) [php/phpt/variables/011-value-casting-operators.phpt] 
FAIL Test Php::Value casting operators (double) [php/phpt/variables/012-value-casting-operators-double.phpt] 
FAIL calling-php-functions from userspace [php/phpt/variables/013-calling-php-functions.phpt] 
FAIL calling-php-Callback-functions [php/phpt/variables/014-calling-php-functions.phpt] 
FAIL calling-php-Callback-functions (lambda) [php/phpt/variables/015-calling-php-functions.phpt] 
FAIL calling-php-Callback-functions (__invoke) [php/phpt/variables/016-calling-php-functions.phpt] 
FAIL calling-php-Callback-functions (method of class) [php/phpt/variables/017-calling-php-functions.phpt] 
PASS calling-php-callable [php/phpt/variables/018-calling-php-functions.phpt] 
PASS get_complex_array (test HashMember #1) [php/phpt/variables/019-HashMember-1.phpt] 
PASS get_complex_array (test HashMember #2) [php/phpt/variables/020-HashMember-2.phpt] 
PASS get_complex_array (test HashMember #3) [php/phpt/variables/021-HashMember-3.phpt] 
PASS get_complex_array (test HashMember #4) [php/phpt/variables/022-HashMember-4.phpt] 
SKIP test cookie [php/phpt/variables/023-cookie.phpt] reason: CGI not available
SKIP test get and post [php/phpt/variables/024-get-post.phpt] reason: CGI not available
SKIP test post raw #1 [php/phpt/variables/025-post-raw1.phpt] reason: CGI not available
SKIP Post files [php/phpt/variables/026-post-raw2.phpt] reason: CGI not available
PASS test superglobal _ENV [php/phpt/variables/027-env.phpt] 
PASS Test bool Value::operator==(const Value &value) const [php/phpt/variables/028-compare1.phpt] 
PASS Test bool Value::operator< (const Value &value) const [php/phpt/variables/029-compare2.phpt] 
=====================================================================
Number of tests :   44                40
Tests skipped   :    4 (  9.1%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    7 ( 15.9%) ( 17.5%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   33 ( 75.0%) ( 82.5%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test Php::Value casting operators (64bit OS only) [php/phpt/variables/011-value-casting-operators.phpt]
Test Php::Value casting operators (double) [php/phpt/variables/012-value-casting-operators-double.phpt]
calling-php-functions from userspace [php/phpt/variables/013-calling-php-functions.phpt]
calling-php-Callback-functions [php/phpt/variables/014-calling-php-functions.phpt]
calling-php-Callback-functions (lambda) [php/phpt/variables/015-calling-php-functions.phpt]
calling-php-Callback-functions (__invoke) [php/phpt/variables/016-calling-php-functions.phpt]
calling-php-Callback-functions (method of class) [php/phpt/variables/017-calling-php-functions.phpt]
=====================================================================
sh: 1: /var/www/html/PHP-CPP/tests/libtool: not found
sh: 1: /var/www/html/PHP-CPP/tests/build/shtool: not found




MAKE FILE  

#
#   PHP-CPP Makefile
#
#   This makefile has a user friendly order: the top part of this file contains 
 

PHP_CONFIG				=	php-config




PHP_BIN					=	$(shell ${PHP_CONFIG} --php-binary)




INSTALL_PREFIX			=	/usr
INSTALL_HEADERS			=	${INSTALL_PREFIX}/include
INSTALL_LIB				=${INSTALL_PREFIX}/lib64



PHP_SHARED_LIBRARY		=	libphpcpp.so
PHP_STATIC_LIBRARY		=	libphpcpp.a
HHVM_SHARED_LIBRARY		=	libhhvmcpp.so
HHVM_STATIC_LIBRARY		=	libhhvmcpp.a




ifdef CXX
 COMPILER				=	${CXX}
 LINKER					=	${CXX}
else
 COMPILER				=	g++
 LINKER					=	g++
endif

ifdef AR
  ARCHIVER				=	${AR} rcs
else
  ARCHIVER				=	ar rcs
endif



COMPILER_FLAGS			=	-Wall -c -g -std=c++11
SHARED_COMPILER_FLAGS	=	-fpic
STATIC_COMPILER_FLAGS	=
PHP_COMPILER_FLAGS		=	${COMPILER_FLAGS} `${PHP_CONFIG} --includes`
HHVM_COMPILER_FLAGS		=	${COMPILER_FLAGS}



LINKER_FLAGS			=	-shared
PHP_LINKER_FLAGS		=	${LINKER_FLAGS} `${PHP_CONFIG} --ldflags`
HHVM_LINKER_FLAGS		=	${LINKER_FLAGS}



RM						=	rm -fr
CP						=	cp -f
MKDIR					=	mkdir -p




COMMON_SOURCES			=	$(wildcard common/*.cpp)
PHP_SOURCES				=	$(wildcard zend/*.cpp)
HHVM_SOURCES			=	$(wildcard hhvm/*.cpp)

COMMON_SHARED_OBJECTS	=	$(COMMON_SOURCES:%.cpp=shared/%.o)
PHP_SHARED_OBJECTS		=	$(PHP_SOURCES:%.cpp=shared/%.o)
HHVM_SHARED_OBJECTS		=	$(HHVM_SOURCES:%.cpp=shared/%.o)
COMMON_STATIC_OBJECTS	=	$(COMMON_SOURCES:%.cpp=static/%.o)
PHP_STATIC_OBJECTS		=	$(PHP_SOURCES:%.cpp=static/%.o)
HHVM_STATIC_OBJECTS		=	$(HHVM_SOURCES:%.cpp=static/%.o)




all: phpcpp

phpcpp: ${PHP_SHARED_LIBRARY} ${PHP_STATIC_LIBRARY}
	@echo
	@echo "Build complete."

hhvmcpp: ${HHVM_SHARED_LIBRARY} ${PHP_STATIC_LIBRARY}
	@echo
	@echo "Build complete."

${PHP_SHARED_LIBRARY}: shared_directories ${COMMON_SHARED_OBJECTS} ${PHP_SHARED_OBJECTS}
	${LINKER} ${PHP_LINKER_FLAGS} -o $@ ${COMMON_SHARED_OBJECTS} ${PHP_SHARED_OBJECTS}

${PHP_STATIC_LIBRARY}: static_directories ${COMMON_STATIC_OBJECTS} ${PHP_STATIC_OBJECTS}
	${ARCHIVER} $@ ${COMMON_STATIC_OBJECTS} ${PHP_STATIC_OBJECTS}

${HHVM_SHARED_LIBRARY}: shared_directories ${COMMON_SHARED_OBJECTS} ${HHVM_SHARED_OBJECTS}
	${LINKER} ${HHVM_LINKER_FLAGS} -o $@ ${COMMON_SHARED_OBJECTS} ${HHVM_SHARED_OBJECTS}

${HHVM_STATIC_LIBRARY}: static_directories ${COMMON_STATIC_OBJECTS} ${HHVM_STATIC_OBJECTS}
	${ARCHIVER} $@ ${COMMON_STATIC_OBJECTS} ${HHVM_STATIC_OBJECTS}

shared_directories:
	${MKDIR} shared/common
	${MKDIR} shared/zend
	${MKDIR} shared/hhvm

static_directories:
	${MKDIR} static/common
	${MKDIR} static/zend
	${MKDIR} static/hhvm

clean:
	${RM} shared ${PHP_SHARED_LIBRARY} ${HHVM_SHARED_LIBRARY}
	${RM} static ${PHP_STATIC_LIBRARY} ${HHVM_STATIC_LIBRARY}
	find -name *.o | xargs ${RM}

${COMMON_SHARED_OBJECTS}: 
	${COMPILER} ${COMPILER_FLAGS} ${SHARED_COMPILER_FLAGS} -o $@ ${@:shared/%.o=%.cpp}

${COMMON_STATIC_OBJECTS}: 
	${COMPILER} ${COMPILER_FLAGS} ${STATIC_COMPILER_FLAGS} -o $@ ${@:static/%.o=%.cpp}

${PHP_SHARED_OBJECTS}: 
	${COMPILER} ${PHP_COMPILER_FLAGS} ${SHARED_COMPILER_FLAGS} -o $@ ${@:shared/%.o=%.cpp}

${PHP_STATIC_OBJECTS}: 
	${COMPILER} ${PHP_COMPILER_FLAGS} ${STATIC_COMPILER_FLAGS} -o $@ ${@:static/%.o=%.cpp}

${HHVM_SHARED_OBJECTS}: 
	${COMPILER} ${HHVM_COMPILER_FLAGS} ${SHARED_COMPILER_FLAGS} -o $@ ${@:shared/%.o=%.cpp}

${HHVM_STATIC_OBJECTS}: 
	${COMPILER} ${HHVM_COMPILER_FLAGS} ${STATIC_COMPILER_FLAGS} -o $@ ${@:static/%.o=%.cpp}

install:
	${MKDIR} ${INSTALL_HEADERS}/phpcpp
	${CP} phpcpp.h ${INSTALL_HEADERS}
	${CP} include/*.h ${INSTALL_HEADERS}/phpcpp
	if [ -e ${PHP_SHARED_LIBRARY} ]; then ${CP} ${PHP_SHARED_LIBRARY} ${INSTALL_LIB}; fi
	if [ -e ${PHP_STATIC_LIBRARY} ]; then ${CP} ${PHP_STATIC_LIBRARY} ${INSTALL_LIB}; fi
	if [ -e ${HHVM_SHARED_LIBRARY} ]; then ${CP} ${HHVM_SHARED_LIBRARY} ${INSTALL_LIB}; fi
	if [ -e ${HHVM_STATIC_LIBRARY} ]; then ${CP} ${HHVM_STATIC_LIBRARY} ${INSTALL_LIB}; fi

test:
	mkdir -p ./tests/include/zts/phpcpp
	cd tests && ./test.sh -p "${PHP_BIN}"

**Comment by afrika042** [comment]
hello all
i'm totally new to PHP-CPP and i want to install it on my VPS
please i need a guide and command on how to do so

thank you

**Comment by afrika042** [comment]
> > i'm totally new to PHP-CPP and i want to install it on my VPS
> > please i need a guide and command on how to do so
> 
> You can getted started with http://www.php-cpp.com/documentation/install

Hello, i have successful installed it on my new server, with php7.0. Now i want to know how to host my files, do i host it as normal root where php files are hosted or do i need to host it in a specific please. Also can i get a demo or tutor? i have check on http://www.php-cpp.com/documentation

**Comment by valmat** [comment]
@afrika042 You need to host it in specific plase. 
PHP-CPP is the library to make php-extentions. So you need to place your _compiled_ files in a special place where extensions are stored.

You should to compile and install your extension to your PHP-extension directory.
To view your extension path you can run the command: `php-config --extension-dir`.
Look at [Makefile example](https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/master/Examples/FunctionReturnValue/Makefile#L7)

More simplify way to build and deploy your extension on your server is using command `checkinstall` instead of `make install`
Run following commands in your source directory
```bash
make
sudo checkinstall -D --install=no
```
checkinstall will create a deb-file which you should to upload on your server.
Then run `dpkg -i <your-deb-file>.deb` on your server to install it.

See more [examples](https://github.com/CopernicaMarketingSoftware/PHP-CPP/tree/master/Examples) as a demo.
