### ISSUE TITLE
Problem with visibility=hidden

### ISSUE THREAD

**Issue by fcool** [CopernicaMarketingSoftware/PHP-CPP#186]
Since 1.3.2 (1.3.1 works fine!) the default building does not work on my gentoo linux. If I try to load a module which uses libphpcpp I get:

Warning: PHP Startup: Unable to load dynamic library '/tmp/PHP-CPP/tests/ext_dir/extfortest.so' - /tmp/PHP-CPP/tests/ext_dir/extfortest.so: undefined symbol: _ZN3Php3GETE in Unknown on line 0

If I remove visibility=hidden everythings works again.

I tried to debug where this symbol comes from, but my c-knowledge is very limited

gcc is 4.8.4 if this is of interest.

**Comment by EmielBruijntjes** [comment]
Yes, we changed the default visibility of all functions, classes, etc to hidden, because that makes loading the PHPCPP library much faster. Only the public symbols are now explicitly made visible. But we may have missed one or two...

Are you sure that you have recompiled your extension too after updating PHPCPP?

I've just committed a change. I dont know if that does the trick, can you test it?

**Comment by fcool** [comment]
Yeah, the unresolved symbol changed... now it is: _ZN3Php7GLOBALSE

And yes: I'm sure i've cleaned everything and recompiled any extension.

**Comment by EmielBruijntjes** [comment]
Ok great, thanks for reporting, that helps everyone and we're getting closes to a solution. Check after my next push, is the problem then solved or is there another symbol that is unresolved?

**Comment by fcool** [comment]
Wooohooo! Everything resolved now. Thanks a lot Emiel!

**Comment by EmielBruijntjes** [comment]
You're welcome :)
