### ISSUE TITLE
Tests doesn't pass

### ISSUE THREAD

**Issue by jonasasx** [CopernicaMarketingSoftware/PHP-CPP#215]
After installing php-cpp, I run `make test`. It has fault:

	mkdir -p tests/include/zts/phpcpp
	cd tests && ./test.sh -p "/usr/bin/php"
	Compile the test extension
	make[1]: Entering directory `/home/ionas/make/PHP-CPP/tests/cpp'
	rm -f extfortest.so main.o
	make[1]: Leaving directory `/home/ionas/make/PHP-CPP/tests/cpp'
	make[1]: Entering directory `/home/ionas/make/PHP-CPP/tests/cpp'
	g++ -Wall -c -O2 -std=c++11 -fpic -I"/home/ionas/make/PHP-CPP/tests/include/lib" -I"/home/ionas/make/PHP-CPP/tests/include/zts" -o main.o main.cpp
	In file included from /home/ionas/make/PHP-CPP/tests/include/lib/phpcpp.h:39:0,
		         from main.cpp:8:
	/home/ionas/make/PHP-CPP/tests/include/lib/phpcpp/type.h:32:1: warning: type attributes ignored after type is already defined [-Wattributes]
	 };
	 ^
	In file included from /home/ionas/make/PHP-CPP/tests/include/lib/phpcpp.h:60:0,
		         from main.cpp:8:
	/home/ionas/make/PHP-CPP/tests/include/lib/phpcpp/classtype.h:31:1: warning: type attributes ignored after type is already defined [-Wattributes]
	 };
	 ^
	g++ -shared -L"/home/ionas/make/PHP-CPP" -o extfortest.so main.o -lphpcpp
	make[1]: Leaving directory `/home/ionas/make/PHP-CPP/tests/cpp'
	/home/ionas/make/PHP-CPP:
	PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so' - /home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so: undefined symbol: _ZN3PhplsERSoRKNS_8IniValueE in Unknown on line 0
	PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so' - /home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so: undefined symbol: _ZN3PhplsERSoRKNS_8IniValueE in Unknown on line 0

	=====================================================================

After that, every test has been skiped.

**Comment by jonasasx** [comment]
If I link this test with `-z defs` param, I have errors:

	g++ -shared -L"/root/make/PHP-CPP" -o extfortest.so main.o -lphpcpp -z defs
	main.o: In function `TestIniEntries::iniTest1(Php::Parameters&)':
	main.cpp:(.text+0xeb): undefined reference to `Php::operator<<(std::ostream&, Php::IniValue const&)'
	main.cpp:(.text+0x13a): undefined reference to `Php::operator<<(std::ostream&, Php::IniValue const&)'
	main.cpp:(.text+0x189): undefined reference to `Php::operator<<(std::ostream&, Php::IniValue const&)'
	main.cpp:(.text+0x1d8): undefined reference to `Php::operator<<(std::ostream&, Php::IniValue const&)'
	main.cpp:(.text+0x227): undefined reference to `Php::operator<<(std::ostream&, Php::IniValue const&)'
	main.o:main.cpp:(.text+0x276): more undefined references to `Php::operator<<(std::ostream&, Php::IniValue const&)' follow
	collect2: error: ld returned 1 exit status

**Comment by alex-laties** [comment]
@jonasasx The issue is as follows: the release builds of `PHP-CPP` create a semantically versioned shared object. In the case of `PHP-CPP` 1.5, `libphpcpp.1.5.0.so` is generated.

When the test php extension is being built, it is being linked with the flag `-lphpcpp`. `ld`, the linker loader, will attempt to look for the shared object `libphpcpp.so` in the specified load directory (in your case `/home/ionas/make/PHP-CPP`). Since `libphpcpp.so` is not in the specified directory, `ld` fails to load the shared library and the test extension consequently gets undefined symbols.

To fix, just create a symlink of `libphpcpp.so` -> `libphpcpp.1.5.0.so`.

I've posted a patch [here](https://gist.github.com/alex-laties/f89fc3c1d8e45d115522) that you can apply to get `make test` doing the right thing. @EmielBruijntjes would it be possible to upstream this Makefile patch?

**Comment by Nek-** [comment]
I tested your patch, nothing work better: http://screencloud.net/v/8lm9

**Comment by EmielBruijntjes** [comment]
I removed the test framework. It was not written by me in the first place, it never works, most of the bugs found by the test framework turned out to be caused by errors in the tests rather than by errors in the real code, people complain about it all the time, and basically this whole test framework causes more problems than it solves.
