### ISSUE TITLE
"make test" doesn't pass

### ISSUE THREAD

**Issue by swapniel99** [CopernicaMarketingSoftware/PHP-CPP#221]
![capture](https://cloud.githubusercontent.com/assets/3740219/9780537/ed2f97ba-57a7-11e5-9ac6-d069856a6794.PNG)

Only one test fails: 
FAIL Test Php::Value overloaded operators [php/phpt/variables/007-overloaded-operators.phpt]

There were no errors or warnings while building. But got below warnings while doing "make test".
![capture](https://cloud.githubusercontent.com/assets/3740219/9780572/1f879fc8-57a8-11e5-897a-196c48ef3b11.PNG)

**Comment by EmielBruijntjes** [comment]
I removed the test framework. It was not written by me in the first place, it never works, most of the bugs found by the test framework turned out to be caused by errors in the tests rather than by errors in the real code, people complain about it all the time, and basically this whole test framework causes more problems than it solves.
