### ISSUE TITLE
How to stop current request without using exit(0)

### ISSUE THREAD

**Issue by dcotet** [CopernicaMarketingSoftware/PHP-CPP#232]
I am creating a simple PHP module with PHP-CPP library.

I make this to limit process per IP address per php script file. I have found a solution for everything I needed, except 1 thing : I cant stop the script cleanly. 

If you look in the script it have exit(0); .. If I use for example Php::echo(); for writing some headers and HTML, that result doesn't get returned to the web browser (nor telnet).

Do you know a method to echo some headers and body then kill the script without executing the final script ?

Thank you very much !

    #include <phpcpp.h>
    #include <iostream>
    #include <fstream>
    #include <stdio.h>  
    
    
    extern "C" {
    	
    	
        PHPCPP_EXPORT void *get_module()     {
        
        
            static Php::Extension extension("dosguard", "0.9");
                    
           
            extension.onShutdown([]() {
            	system("rm -r /dev/shm/dosguard-*");
            });
    		
            extension.onRequest([]() {
    			
    			std::string inode = Php::call("fileinode", Php::SERVER["SCRIPT_FILENAME"]);
    			std::string ip = Php::SERVER["REMOTE_ADDR"];
    			int time = Php::call("time");
    			
    			std::string shm = "/dev/shm/dosguard-"+inode+"@"+ip+".time";
    			
    			int saved = Php::call("file_get_contents", shm);
    	    	
    	    	if(saved >= time)	{
    	    	
                    //////////////////////////////////////////
    				exit(0);
                    //////////////////////////////////////////
    			
    	    	}	else	{
    	    	
    	    		if(saved == NULL)	{
    	    			saved = time;
    	    		}
    	    		else	{
    	    			saved = time + 1;
    	    		}
    	    		
    	    		Php::call("file_put_contents", shm, saved);
    	    	
    	    	}
    			
            });
    		
            
            return extension;
        }
    }

**Comment by hugdx** [comment]
try to replace `` exit(0);`` with ``Php::eval("die();");``

**Comment by dcotet** [comment]
I have just tried this, not solving the problem S:

2015-12-02 3:11 GMT-05:00 hugdx <notifications@github.com>:

> try to replace exit(0); with Php::eval("die();");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/232#issuecomment-161215259>
> .
>



-- 
David Côté-Tremblay
Programmeur Web / Administrateur Linux
imdc.technologies@gmail.com

Services corporatifs : http://www.solib.ca/
Réparation d'ordinateurs : http://particuliers.solib.ca/
Blogue : http://www.dctremblay.com/
Twitter : http://twitter.com/DavidCTremblay
Facebook : https://www.facebook.com/dctremblay007

**Comment by EmielBruijntjes** [comment]
I'm sorry to say this, but your code does not look very nice. PHP-CPP is a library to move away from PHP space into C++ space. If you need the "Php::call()" function to call back to PHP functions, you have a very clear signal that you are *probably* doing something completely wrong here.

What is all wrong? 

````Php::call("time")```` : Don't call that, C++ has its own functions and classes to find out the time!
````Php::call("file_get_contents")```` : C++ has its own functions and classes to read file data!
````Php::call("file_put_contents")```` : C++ has its own functions and classes to write to files!

Why do you even think of calling "exit()" from a PHP extension. This would fatally kill your entire web server - and it is more than likely that you do not want to do such a bold thing. An extension should not have side effects like this, it should not kill its parent process: it is just meant to expose additional features to your PHP scripts - not to kill them!

Apart from the fact that it is *remarkable* that you use a C++ extension for programming something that could just have well been written as a PHP script (especially since you're not at all using specific C++ features or libraries, or doing high CPU intensive calculations), the way how you implement it is strange too. Why do you remove files in the "onShutdown()" function in the first place? The onShutdown() function runs all the time when new web server processes are started or stopped. You probably don't want to do this.

There is a very good guideline when you want to use PHP-CPP: when you are a C++ programmer and want to use a specific feature from C++. If you're a PHP programmer who just likes to calll functions from PHP, and work with variables in PHP, there is no point in using PHP-CPP at all.

**Comment by dcotet** [comment]
Hi, not be so easily shocked, I am allowed to be a beginner with that
library isn't it ? You can consider it as a simple test =) No intend for
production at the moment that's why there are wrong stuff ! I will clean
the source code when my question will be answered (how to render custom
headers and body and cancel executing the PHP script)

I am creating a custom extension because I want that script to be executed
before every-single-php scripts on all virtualhosts, and also have very
good performances (the function that I use in PHP are wrote in C or C++ am
I wrong?) those are already loaded in memory with PHP so may be very much
faster.

I am a C++ programmer too but for a simple scratch test for exemple, isn't
appropriate to use the most straightforward method ? (using PHP functions)

Hope someone can answer my question !

Thank you very much and have a great day ! =)

2015-12-07 12:28 GMT-05:00 Emiel Bruijntjes <notifications@github.com>:

> I'm sorry to say this, but your code does not look very nice. PHP-CPP is a
> library to move away from PHP space into C++ space. If you need the
> "Php::call()" function to call back to PHP functions, you have a very clear
> signal that you are *probably* doing something completely wrong here.
>
> What is all wrong?
>
> Php::call("time") : Don't call that, C++ has its own functions and
> classes to find out the time!
> Php::call("file_get_contents") : C++ has its own functions and classes to
> read file data!
> Php::call("file_put_contents") : C++ has its own functions and classes to
> write to files!
>
> Why do you even think of calling "exit()" from a PHP extension. This would
> fatally kill your entire web server - and it is more than likely that you
> do not want to do such a bold thing. An extension should not have side
> effects like this, it should not kill its parent process: it is just meant
> to expose additional features to your PHP scripts - not to kill them!
>
> Apart from the fact that it is *remarkable* that you use a C++ extension
> for programming something that could just have well been written as a PHP
> script (especially since you're not at all using specific C++ features or
> libraries, or doing high CPU intensive calculations), the way how you
> implement it is strange too. Why do you remove files in the "onShutdown()"
> function in the first place? The onShutdown() function runs all the time
> when new web server processes are started or stopped. You probably don't
> want to do this.
>
> There is a very good guideline when you want to use PHP-CPP: when you are
> a C++ programmer and want to use a specific feature from C++. If you're a
> PHP programmer who just likes to calll functions from PHP, and work with
> variables in PHP, there is no point in using PHP-CPP at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/232#issuecomment-162600300>
> .
>



-- 
David Côté-Tremblay
Programmeur Web / Administrateur Linux
imdc.technologies@gmail.com

Services corporatifs : http://www.solib.ca/
Réparation d'ordinateurs : http://particuliers.solib.ca/
Blogue : http://www.dctremblay.com/
Twitter : http://twitter.com/DavidCTremblay
Facebook : https://www.facebook.com/dctremblay007

**Comment by EmielBruijntjes** [comment]
- execute script before every other script: http://websistent.com/php-auto_prepend_file-and-auto_append_file/
- good performance tip 1: switching to C++ for a better performance only make sense if you currently have a poor performance
- good performance tip 2: inside C++, calling Php::something always has poor performance because you switch back to PHP space
