### ISSUE TITLE
Php::Script fails from the std::thread

### ISSUE THREAD

**Issue by slidertom** [CopernicaMarketingSoftware/PHP-CPP#264]
Php::Script fails (zend string allocation) from the std::thread

```
void TestScript() {
   const std::string sCommand = "return $_SERVER['SERVER_PORT'];";
   Php::Script(sCommand.c_str()).execute();
}
std::thread th(TestScript);
th.join();

```
but if I do call from the any PHP_FUNCTION -> everything works.

**Comment by EmielBruijntjes** [comment]
Don't use threads.

**Comment by aftabnaveed** [comment]
@EmielBruijntjes but the documention mentions it as one of its features: 

> 5. Support for all the important PHP features
> With PHP-CPP you can work with variables, arrays, functions, objects, classes, interfaces, exceptions and namespaces just as easily as you can with normal PHP scripts. Besides that, you can use all features of C++, including threads, lambdas and asynchronous programming.

**Comment by mvdwerve** [comment]
@aftabnaveed I think you misunderstand. While it is true that everything from PHP to CPP is supported with regard to threads (you have to really think about thread safety there anyway, because there is some weird stuff happening with the modules and loading), it's an entirely different story calling things such as Php::Script from C++ code. Those are not thread-safe afaik, so proper locking is required so that only the main thread ever calls the PHP parts.

Maybe the ZTS version is thread safe? Maybe check it out there, but then the PHP-CPP objects itself aren't thread-safe either afaik.

**Comment by aftabnaveed** [comment]
Thank you @mvdwerve  I get it now we should not be calling php scripts or user land PHP functions inside C++ anyway that. That kills the purpose of using PHP-CPP in first place. 

However, I created an issue here to do some threading in my C++ application https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/383   but I could not find any example can you please help? 

Thank you.

**Comment by sjinks** [comment]
In your extension, you can use threads inside a function to do some heavy work (just like ImageMagick does). However, threads should not be exposed to PHP userland, nor can C++ threads call PHP functions (this could be possible with ZTS, but you will need to install custom hooks to handle all threading stuff or have a custom SAPI).
